# https://github.com/rhea-so/tsdoc-github-wiki-example

name: Sync GitHub Wiki

on:
  push:
    branches: develop

jobs:
  localize-build-test-docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@main
        with:
          node-version: 23

      - name: Cache Dependencies
        id: cache
        uses: actions/cache@main
        with:
          key: ${{ hashFiles('package-lock.json') }}
          path: "node_modules"

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Localize
        run: npm run localize

      - name: Build
        run: npm run build

      - name: Test
        run: npm run test

      - name: Docs
        run: npm run docs

      - name: GitHub Wiki
        uses: spenserblack/actions-wiki@main
        with:
          path: wiki